Launch next-gen correlator tasks
ska-sa/katsdpcontroller pull request #532
Opened 2021-07-06 12:26 UTC by bmerry

Closes NGC-190.

2021-07-09 12:02 UTC, james-smith-za requested changes
Mainly related to the merge/rename of the modules.

2021-07-09 12:12 UTC, bmerry commented
I'm going to suggest that for this PR I stick with the "katfgpu" and "katxgpu" Docker images. They're in the Docker registry, so this will continue to work but just use those old versions (which at least are known to work right now).

When I switch to using katgpucbf there will be a few other changes e.g. to wire up the katcp port on fgpu. Rather than continually trying to keep this PR up to date with the refactoring on katgpucbf I'd like to get this merged and then start new PRs for updates.

I've only glanced at the other comments, but they sound reasonable. Will come back to them later, probably next week.

2021-07-09 12:21 UTC, james-smith-za commented
> 
> 
> I'm going to suggest that for this PR I stick with the "katfgpu" and "katxgpu" Docker images. They're in the Docker registry, so this will continue to work but just use those old versions (which at least are known to work right now).
> 
> When I switch to using katgpucbf there will be a few other changes e.g. to wire up the katcp port on fgpu. Rather than continually trying to keep this PR up to date with the refactoring on katgpucbf I'd like to get this merged and then start new PRs for updates.
> 
That's quite reasonable. I'm good with that. The remaining stuff was very minor.

2021-07-11 12:16 UTC, bmerry commented on katsdpcontroller/generator.py
> +        xgpu.katsdpservices_logging = False
Indeed.

2021-07-11 12:19 UTC, bmerry commented on katsdpcontroller/scheduler.py
> +    min_compute_capability : Tuple[int], optional
You're quite right. I might have been intending of `Tuple[int, ...]` (variable-length tuple of ints), but compute capabilities are always two components so I'll change it.

2021-07-11 12:21 UTC, bmerry commented on katsdpcontroller/product_config.py
> +        return 10
I'm not sure - have changed it as suggested.

2021-07-12 05:43 UTC, james-smith-za approved these changes

2021-07-12 06:44 UTC, merged