{src, dst} -> {recv, send} for GPU CBF
ska-sa/katsdpcontroller pull request #745
Opened 2024-06-18 13:53 UTC by amishatishpatel

Contributes to: NGC-1158.

2024-06-18 14:13 UTC, bmerry requested changes
Looks reasonable to me - obviously will need to be matched with a katgpucbf PR. I've got one suggestion to extend the change a little further into the katsdpcontroller code.

2024-06-18 14:13 UTC, bmerry commented on src/katsdpcontroller/generator.py
>                  "{cores[src]}",
I think rename the cores as well (line 664).

2024-06-18 14:13 UTC, bmerry commented on src/katsdpcontroller/generator.py
> +            xbgpu.command += ["--recv-affinity", "{cores[src]}", "--send-affinity", "{cores[dst]}"]
Again, rename the cores (line 1123).

2024-06-18 14:24 UTC, amishatishpatel commented
Thanks for being so quick on this, and with an excellent suggestion too.

Corresponding katgpucbf PR is up for review.

2024-06-19 08:34 UTC, james-smith-za approved these changes
LGTM.


@bmerry made a good suggestion so IMO once you've incorporated that and the tests pass, I'd say go ahead and merge.

2024-06-19 09:03 UTC, bmerry approved these changes

2024-06-19 09:40 UTC, merged